### ISSUE TITLE
无扩展名文件如何打开？

### ISSUE THREAD

**Issue by Tochase** [Exely/WD-Data-Structure#1]
![image](https://user-images.githubusercontent.com/15307280/41136600-91901b50-6b09-11e8-8000-38c570f3b79e.png)
你好，同 19 计算机考研。
请问像上图中的  2-2-9  这样无拓展名的文件是用什么编辑的？要如何查看呢？

**Comment by Exely** [comment]
这是gcc或g++编译后的可执行文件，在Unix环境下使用命令` ./2-2-9` 即可运行；
在Windows环境下，建议重新编译，对应的源文件就是同名的C或Cpp文件。
可执行程序本来不应该放在git上的，只是我懒得删……

**Comment by Tochase** [comment]
ok，明白了，多谢回复
